source "https://github.com/TaranWu/Go23WalletSpec.git"
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '13.0'

target 'Go23EthereumABI_Example' do
  pod 'Go23EthereumABI', :path => '../'

  target 'Go23EthereumABI_Tests' do
    inherit! :search_paths

    
  end
end
